version: '3'
services:
  reversible_web:
    command: bundle exec rails server -b 0.0.0.0 -p 80
    restart: always
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    networks:
      - default
      - applications
  postgres:
    image: postgres:12-alpine
    restart: always
    platform: linux/arm64
    networks:
      - default
    volumes:
      - reversible_pg_data:/var/lib/postgresql/data 
  redis:
    image: redis
    platform: linux/arm64
    networks:
      - default
    restart: always

volumes:
  reversible_pg_data:
    external: true

networks:
  applications:
    external: true
